spring.application.name=CapaDocAPI

# URL: Falls SPRING_DATASOURCE_URL nicht gesetzt ist, nimm localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${DB_NAME:capadoc_db}}

# Zugangsdaten: Werden zur Laufzeit dynamisch aus den Variablen gelesen
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:capadoc_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

spring.jpa.hibernate.ddl-auto=update